# Generated by Django 4.1.1 on 2022-11-21 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_request_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reward',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='報酬'),
        ),
    ]
