# Generated by Django 4.1.1 on 2022-11-21 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_request_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reward',
            field=models.DecimalField(decimal_places=5, default=1e-05, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(100)], verbose_name='報酬'),
        ),
    ]
